"""Public contract surface. Import from here, not from submodules."""

from .base import (
    ArtifactClass,
    ChangeSeverity,
    Contract,
    Role,
    SemVer,
    canonical_json,
    digest_of,
    utcnow,
)
from .gate import (
    AdmissionDecision,
    Finding,
    GateId,
    GateResult,
    GateStatus,
    HardGateReport,
    JudgeSample,
    SoftGateResult,
    SoftVerdict,
)
from .governance import (
    DowngradeTrigger,
    HealthMetrics,
    HealthThresholds,
    MigrationStage,
    ProposalKind,
    RuleChangeProposal,
)
from .instance import (
    DifferentialReport,
    Divergence,
    DivergenceVerdict,
    EquivalenceClass,
    InstanceManifest,
    InstanceReport,
    Observation,
    ProbeResult,
)
from .oracle import (
    GoldenRecord,
    HoldoutOracle,
    JudgeProtocol,
    MetamorphicRelation,
    MutationProbe,
    ObservationChannel,
    OracleBundle,
    OracleGrade,
    PropertySpec,
    PublicOracle,
    RubricCriterion,
    Scenario,
    ScenarioKind,
)
from .spec import (
    Anchor,
    Clause,
    ClauseStatus,
    DeltaOp,
    DontCareCategory,
    DontCareRegion,
    FreedomTrack,
    PropertyKind,
    RegenerationUnit,
    RLevel,
    RLevelRegistry,
    SpecDelta,
    SpecDeltaItem,
    SpecDocument,
    SpecLayer,
    WitnessBinding,
    WitnessKind,
)
from .wave import (
    EvidenceReceipt,
    FanoutPlan,
    PipelineKind,
    UncertaintySignal,
    WaveManifest,
    WaveStatus,
)

#: Every contract class, keyed by name. Used by the schema exporter, the bus
#: registry and the round-trip conformance tests. A contract that is not in this
#: registry cannot cross a team boundary.
CONTRACT_REGISTRY: dict[str, type[Contract]] = {
    c.__name__: c
    for c in (
        Anchor,
        Clause,
        WitnessBinding,
        DontCareRegion,
        SpecDocument,
        SpecDelta,
        SpecDeltaItem,
        RegenerationUnit,
        RLevelRegistry,
        Scenario,
        PropertySpec,
        MetamorphicRelation,
        GoldenRecord,
        RubricCriterion,
        JudgeProtocol,
        MutationProbe,
        PublicOracle,
        HoldoutOracle,
        OracleBundle,
        Observation,
        ProbeResult,
        InstanceManifest,
        InstanceReport,
        Divergence,
        EquivalenceClass,
        DifferentialReport,
        Finding,
        GateResult,
        JudgeSample,
        SoftGateResult,
        HardGateReport,
        AdmissionDecision,
        UncertaintySignal,
        FanoutPlan,
        WaveManifest,
        EvidenceReceipt,
        HealthThresholds,
        HealthMetrics,
        RuleChangeProposal,
    )
}

__all__ = sorted(
    [
        *CONTRACT_REGISTRY,
        "ArtifactClass",
        "ChangeSeverity",
        "Contract",
        "Role",
        "SemVer",
        "canonical_json",
        "digest_of",
        "utcnow",
        "GateId",
        "GateStatus",
        "SoftVerdict",
        "DivergenceVerdict",
        "ObservationChannel",
        "OracleGrade",
        "ScenarioKind",
        "SpecLayer",
        "PropertyKind",
        "FreedomTrack",
        "DontCareCategory",
        "ClauseStatus",
        "WitnessKind",
        "DeltaOp",
        "RLevel",
        "PipelineKind",
        "WaveStatus",
        "MigrationStage",
        "DowngradeTrigger",
        "ProposalKind",
        "CONTRACT_REGISTRY",
    ]
)
