SCHEMA_VERSION = "1.0.0"

ROLE_LEADER = "leader"
ROLE_ARCHITECT = "architect"
ROLE_BUILDER = "builder"
ROLE_VERIFIER = "verifier"
ROLE_SPEC_MODERATOR = "spec_moderator"
ROLE_SPEC_STEWARD = "spec_steward"
ROLE_RECONCILER = "reconciler"
ROLE_CARTOGRAPHER = "cartographer"
ROLE_CRITIC = "critic"
ROLE_REFACTOR = "refactor"
ROLE_MODERATOR = "moderator"
ROLE_DEEP_AGENT = "deep_agent"
ROLE_JUDGE = "judge"

ALL_ROLES = (
    ROLE_LEADER,
    ROLE_ARCHITECT,
    ROLE_BUILDER,
    ROLE_VERIFIER,
    ROLE_SPEC_MODERATOR,
    ROLE_SPEC_STEWARD,
    ROLE_RECONCILER,
    ROLE_CARTOGRAPHER,
    ROLE_CRITIC,
    ROLE_REFACTOR,
    ROLE_MODERATOR,
    ROLE_DEEP_AGENT,
    ROLE_JUDGE,
)

GENERATOR_ROLES = (ROLE_BUILDER,)
DISCRIMINATOR_ROLES = (ROLE_VERIFIER, ROLE_JUDGE, ROLE_SPEC_MODERATOR)
