from .base import (
    Confidentiality,
    ContractEnvelope,
    ContractModel,
    JUDGE_ROLES,
    GENERATOR_ROLES,
    RLevel,
    Role,
    SPEC_ROLES,
    SpecLevel,
    Verdict,
    new_id,
    utc_now_iso,
)
from .spec import (
    BCClass,
    ChangeOp,
    ClauseChange,
    ClauseStatus,
    DontCareDeclaration,
    DontCareKind,
    MachineContract,
    SpecClause,
    SpecDelta,
    SpecDoc,
    WitnessKind,
    canonical_clause_digest,
)
from .gates import GateId, GateResult, GateSuiteResult, WitnessRef, HARD_GATES
from .oracle import (
    BiasControls,
    EvidenceCitation,
    HoldoutScenario,
    JudgeVerdict,
    JudgeVerdictKind,
    Rubric,
    RubricItem,
    ScenarioGrading,
    ScenarioOutcome,
)
from .fanout import (
    DiscardedInstance,
    FanoutRequest,
    InstanceSubmission,
    MeasurementClassification,
    MeasurementEvent,
)
from .wave import FrozenInterface, WavePlan, WaveStage
from .admission import AdmissionDecision, DriftCheckSummary, EvidenceReceipt, LedgerEntry
from .drift import AnchorRecord, AnchorState, DriftEvent, DriftSeverity
from .evolution import ProposalStatus, RuleProposal
from .health import HealthSnapshot, MigrationStage

CONTRACT_REGISTRY: dict[str, type[ContractModel]] = {
    cls.__name__: cls
    for cls in [
        ContractEnvelope,
        SpecClause,
        SpecDoc,
        SpecDelta,
        ClauseChange,
        DontCareDeclaration,
        MachineContract,
        GateResult,
        GateSuiteResult,
        WitnessRef,
        HoldoutScenario,
        ScenarioOutcome,
        Rubric,
        RubricItem,
        BiasControls,
        JudgeVerdict,
        EvidenceCitation,
        FanoutRequest,
        InstanceSubmission,
        DiscardedInstance,
        MeasurementEvent,
        WavePlan,
        FrozenInterface,
        EvidenceReceipt,
        AdmissionDecision,
        LedgerEntry,
        DriftCheckSummary,
        AnchorRecord,
        DriftEvent,
        RuleProposal,
        HealthSnapshot,
    ]
}

__all__ = [
    "CONTRACT_REGISTRY",
    "Confidentiality",
    "ContractEnvelope",
    "ContractModel",
    "Role",
    "RLevel",
    "SpecLevel",
    "Verdict",
    "SpecClause",
    "SpecDoc",
    "SpecDelta",
    "ClauseChange",
    "ChangeOp",
    "BCClass",
    "ClauseStatus",
    "DontCareDeclaration",
    "DontCareKind",
    "MachineContract",
    "WitnessKind",
    "GateId",
    "GateResult",
    "GateSuiteResult",
    "WitnessRef",
    "HARD_GATES",
    "HoldoutScenario",
    "ScenarioOutcome",
    "ScenarioGrading",
    "Rubric",
    "RubricItem",
    "BiasControls",
    "JudgeVerdict",
    "JudgeVerdictKind",
    "EvidenceCitation",
    "FanoutRequest",
    "InstanceSubmission",
    "DiscardedInstance",
    "MeasurementEvent",
    "MeasurementClassification",
    "WavePlan",
    "FrozenInterface",
    "WaveStage",
    "EvidenceReceipt",
    "AdmissionDecision",
    "LedgerEntry",
    "DriftCheckSummary",
    "AnchorRecord",
    "AnchorState",
    "DriftEvent",
    "DriftSeverity",
    "RuleProposal",
    "ProposalStatus",
    "HealthSnapshot",
    "MigrationStage",
]
